image: jeroenknoops/java8-groovy-chrome-xvfb

before_script:
  - sleep 3
  - wget http://downloads.arduino.cc/arduino-1.6.9-linux64.tar.xz
  - tar xvf arduino-1.6.9-linux64.tar.xz

compile:

  script:
    - echo Verifying
    - ./arduino-1.6.9/arduino --verify --board arduino:avr:mega:atmega2560 Ner_Lighting_System.ino